import Foundation
@testable import LibraKit
import Testing
import simd

@Suite struct ExportTests {
    /// A 1 kg 0.1 m cube centered at (1, 0, 0) and a part with no mass, in one group whose frame sits at (1, 0, 0)
    /// turned a quarter about Z.
    static var document: LibraDocument {
        let cube = Fixtures.boxPart(name: "Cube", size: [0.1, 0.1, 0.1], corner: [0.95, -0.05, -0.05], mass: 1)
        let loose = Fixtures.boxPart(name: "Loose", size: [0.1, 0.1, 0.1], corner: [2, 0, 0])
        let frame = Frame.file.moved(to: [1, 0, 0]).rotatedQuarterTurn(about: .z)
        return LibraDocument(
            parts: [cube, loose],
            groups: [PartGroup(name: "Arm Link", partIDs: [cube.id, loose.id], frame: frame)]
        )
    }

    static var report: MassReport { MassReport(document: document, modelName: "Test Robot") }

    @Test func reportExpressesGroupInItsFrame() throws {
        let group = try #require(Self.report.groups.first)
        expectClose(group.position, [1, 0, 0])
        expectClose(group.summary.properties.centerOfMass, [0, 0, 0], tolerance: 1e-12)
        expectClose(group.summary.properties.mass, 1)
        #expect(group.summary.unassignedCount == 1)
    }

    @Test func mjcf() {
        let inertia = 1.0 * (0.01 + 0.01) / 12
        let expected = """
        <!-- Generated by Libra. SI units (m, kg, kg·m²). Body poses are relative to the Libra frame;
             each inertial is in its body's frame. Add joints and nest bodies to build the kinematic tree. -->
        <mujoco model="Test Robot">
          <worldbody>
            <body name="Arm_Link" pos="1 0 0" quat="0.707106781 0 0 0.707106781">
              <inertial pos="0 0 0" mass="1" fullinertia="\(ExportFormat.number(inertia)) \(ExportFormat.number(inertia)) \(ExportFormat.number(inertia)) 0 0 0"/>
              <!-- 1 of 2 parts have no mass and are left out -->
            </body>
          </worldbody>
        </mujoco>

        """
        #expect(ExportKind.mjcf.text(for: Self.report) == expected)
    }

    @Test func urdf() {
        let text = ExportKind.urdf.text(for: Self.report)
        #expect(text.contains("<robot name=\"Test_Robot\">"))
        #expect(text.contains("<link name=\"Arm_Link\">"))
        #expect(text.contains("rpy=\"0 0 1.57079633\""))
        #expect(text.contains("<mass value=\"1\"/>"))
        #expect(text.contains("<origin xyz=\"0 0 0\" rpy=\"0 0 0\"/>"))
    }

    @Test func csvHasRowPerAssemblyGroupAndPart() {
        let lines = ExportKind.csv.text(for: Self.report).split(separator: "\n")
        #expect(lines.count == 1 + 1 + 1 + 2)
        #expect(lines[0] == Substring(CSVExporter.header))
        #expect(lines[2].hasPrefix("group,Arm Link,group,1,"))
        // The massless part has empty values and counts as having no mass
        #expect(lines[4] == "part,Loose,libra,,,,,,,,,,,1")
    }

    @Test func jsonParses() throws {
        let data = Data(ExportKind.json.text(for: Self.report).utf8)
        let object = try #require(try JSONSerialization.jsonObject(with: data) as? [String: Any])
        let groups = try #require(object["groups"] as? [[String: Any]])
        #expect(groups.first?["name"] as? String == "Arm Link")
        #expect((object["parts"] as? [Any])?.count == 2)
    }

    @Test func noGroupsExportsWholeAssembly() {
        var document = Self.document
        document.groups = []
        let report = MassReport(document: document, modelName: "Robot")
        #expect(report.groups.count == 1)
        #expect(report.groups[0].name == "Robot")
        #expect(report.groups[0].partNames.count == 2)
    }

    @Test func rollPitchYawRoundTrips() {
        let rotation = simd_double3x3(simd_quatd(angle: 0.3, axis: [0, 0, 1]) * simd_quatd(angle: -0.4, axis: [0, 1, 0]) * simd_quatd(angle: 0.5, axis: [1, 0, 0]))
        let angles = ExportFormat.rollPitchYaw(rotation)
        expectClose(angles[0], 0.5)
        expectClose(angles[1], -0.4)
        expectClose(angles[2], 0.3)
    }

    @Test func identifiersAreSafeAndUnique() {
        #expect(ExportFormat.identifiers(for: ["Hub v3:1", "Hub v3:1", ""]) == ["Hub_v3_1", "Hub_v3_1_2", "group"])
    }
}

@Suite struct DocumentTests {
    @Test func roundTripsThroughJSON() throws {
        var document = ExportTests.document
        document.parts[0].mass = 0.2
        document.libraFrame = Frame.file.moved(to: [0.1, 0.2, 0.3])
        let decoded = try LibraDocument.decoded(from: document.encoded())
        #expect(decoded == document)
    }

    @Test func rejectsNewerFormat() throws {
        var document = LibraDocument()
        document.formatVersion = LibraDocument.currentFormatVersion + 1
        let data = try document.encoded()
        #expect(throws: LibraDocument.FormatError.self) {
            try LibraDocument.decoded(from: data)
        }
    }
}
